### ISSUE TITLE
R.methodsS3  crashes R during installation when valgrind active

### ISSUE THREAD

**Issue by ms609** [HenrikBengtsson/R.methodsS3#21]
Hello,

I'm trying to debug an issue I observe during a [workflow](https://github.com/ms609/TreeTools/actions/runs/4007050092) I've set up to test a package through valgrind.

When I configure R with
```sh
        export LD_PRELOAD=$(gcc -print-file-name=libasan.so)
        mkdir ~/.R
        echo "LDFLAGS = -g -fsanitize=address -fno-omit-frame-pointer" >> ~/.R/Makevars
```

and then proceed in install R and R.methodsS3 using GitHub Actions workflows

```yml

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release

    - name: Set up R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: |
          any::devtools
```

I see

```
ℹ Building R.methodsS3 1.8.2
  R session crashed with exit code 1
  NULL
  NULL
  NULL
  10701
  1674751440
  0                                                            , 1                                                            , 2                                                            , TRUE                                                         , TRUE                                                         , TRUE                                                         , NA                                                           , pak                                                          , NA                                                           ,                                                              , :::                                                          ,                                                              , 10701                                                        , 10701                                                        , 10701                                                        , pak::lockfile_install(".github/pkg.lock")                    , remote(function(...) {                                       ,     get("lockfile_install_internal", asNamespace("pak"))(...), err$throw(res$error)
```

It looks like the issue is related to building R.methodsS3, but I'm not clear exactly where the issue might lie (potentially an interaction with 'pak'?)
